---

- name: cli_command
  cli_command:
    commands: "{{item.command}}"
  ignore_unreachable: true
  ignore_error: true
  register: command_result


- name: debug
  debug:
    msg:
      - " 지시어: {{ item.command }}"
      - " 결과: {{ command_result.stdout}}"



- name: filtering
  shell: /usr/bin/python3 ../vars/filter.py
  environment:
    - hostname: "{{ cisco.hostname }}"
    - host: "{{cisco.hostname }}"
    - total_item: "{{ command_result.stdout }}"
    - id: "{{ item.id }}"
    - message: "{{ item.message }}"
    - value: "{{item.value}}"
    - report_type: "{{report}}"
    - command: "{{ item.command }}"
    - name: "{{ item.name }}"
    - system: "{{system}}"

  delegate_to: localhost 
  register: data
  when: command_result.stdout is defined


- name: merging
  set_fact:
    merged: "{{ merged | default({}) | from_json }}"

- name: merged_value
  set_fact: 
    merged_value: "{{ merged_value + [merged] }}"

